language: go
go: 1.14.6

jobs:
  include:
    - stage: service-test
      name: "API Tests"
      services: redis
      env:
        - REDIS_HOST=127.0.0.1:6379
        - REDIS_PASSWORD=""
      script:
        - go test -v service/*.go
    - stage: api-test
      name: "API Tests"
      services: redis
      env:
        - REDIS_HOST=127.0.0.1:6379
        - REDIS_PASSWORD=""
      script:
        - go test -v api/*.go
    - stage: test-coverage
      name: "Test Coverage"
      services: redis
      env:
        - REDIS_HOST=127.0.0.1:6379
        - REDIS_PASSWORD=""
      script:
        - go test ./... -coverprofile=coverage.out -covermode=atomic
        - go tool cover -html=coverage.out -o coverage.html
    - stage: build
      name: "Docker Build"
      services: docker
      script:
        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        - docker build -t monogradient/go-tracker-api:latest .
        - docker tag monogradient/go-tracker-api:latest monogradient/go-tracker-api:$TRAVIS_BUILD_NUMBER
        - docker push monogradient/go-tracker-api
        - docker logout
    - stage: deploy
      name: "Deploy to Heroku"
      script:
        - echo "TBI"
